spring:
  application:
    name: big-chat-brasil
  datasource:
    url: jdbc:postgresql://localhost:5432/db-bbc
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    filter:
      ignore:
        urls:
          - /v3/api-docs/**
          - /swagger-ui/**
          - /swagger-resources/**
          - /webjars/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: br.com.bcb.api

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG